"""esquema inicial

Revision ID: dd2ee59368e5
Revises: 
Create Date: 2026-08-19 19:33:08.386564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dd2ee59368e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id_rol', mysql.TINYINT(display_width=3, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=180), nullable=False),
    sa.Column('activo', mysql.TINYINT(display_width=1), server_default=sa.text('1'), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id_rol')
    )
    op.create_index('uq_roles_nombre', 'roles', ['nombre'], unique=True)
    op.create_table('servicios',
    sa.Column('id_servicio', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('categoria', sa.Enum('Cortes', 'Barba', 'Combos', 'Tratamientos', 'Infantil', name='servicioscategoria'), server_default=sa.text("'Cortes'"), nullable=False),
    sa.Column('precio', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('duracion_minutos', mysql.SMALLINT(display_width=5, unsigned=True), nullable=False),
    sa.Column('puntos_otorga', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text('0'), nullable=False),
    sa.Column('popular', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=False),
    sa.Column('activo', mysql.TINYINT(display_width=1), server_default=sa.text('1'), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('icono', sa.String(length=80), nullable=True),
    sa.Column('imagen_url', sa.String(length=255), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('NULL ON UPDATE current_timestamp()'), nullable=True),
    sa.CheckConstraint('`duracion_minutos` > 0', name='chk_servicios_duracion'),
    sa.CheckConstraint('`precio` > 0', name='chk_servicios_precio'),
    sa.PrimaryKeyConstraint('id_servicio')
    )
    op.create_index('idx_servicios_activo', 'servicios', ['activo'], unique=False)
    op.create_index('idx_servicios_categoria', 'servicios', ['categoria'], unique=False)
    op.create_index('idx_servicios_popular', 'servicios', ['popular'], unique=False)
    op.create_index('uq_servicios_nombre', 'servicios', ['nombre'], unique=True)
    op.create_table('catalogo_cortes',
    sa.Column('id_corte', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('popular', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=False),
    sa.Column('activo', mysql.TINYINT(display_width=1), server_default=sa.text('1'), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('id_servicio', mysql.BIGINT(display_width=20, unsigned=True), nullable=True),
    sa.Column('categoria', sa.String(length=80), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('imagen_url', sa.String(length=255), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('NULL ON UPDATE current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicios.id_servicio'], name='fk_catalogo_servicio', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_corte')
    )
    op.create_index('idx_catalogo_activo', 'catalogo_cortes', ['activo'], unique=False)
    op.create_index('idx_catalogo_categoria', 'catalogo_cortes', ['categoria'], unique=False)
    op.create_index('idx_catalogo_popular', 'catalogo_cortes', ['popular'], unique=False)
    op.create_index('idx_catalogo_servicio', 'catalogo_cortes', ['id_servicio'], unique=False)
    op.create_table('usuarios',
    sa.Column('id_usuario', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('id_rol', mysql.TINYINT(display_width=3, unsigned=True), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('correo', sa.String(length=180), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=255), nullable=False),
    sa.Column('activo', mysql.TINYINT(display_width=1), server_default=sa.text('1'), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('telefono', sa.String(length=25), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('email_verificado_at', sa.DateTime(), nullable=True),
    sa.Column('ultimo_login_at', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('NULL ON UPDATE current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], name='fk_usuarios_roles', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index('idx_usuarios_activo', 'usuarios', ['activo'], unique=False)
    op.create_index('idx_usuarios_nombre', 'usuarios', ['nombre'], unique=False)
    op.create_index('idx_usuarios_rol', 'usuarios', ['id_rol'], unique=False)
    op.create_index('uq_usuarios_correo', 'usuarios', ['correo'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id_audit', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('entidad', sa.String(length=100), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('id_usuario', mysql.BIGINT(display_width=20, unsigned=True), nullable=True),
    sa.Column('entidad_id', mysql.BIGINT(display_width=20, unsigned=True), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('detalles', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='fk_audit_logs_usuario', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_audit')
    )
    op.create_index('idx_audit_accion', 'audit_logs', ['accion'], unique=False)
    op.create_index('idx_audit_entidad', 'audit_logs', ['entidad', 'entidad_id'], unique=False)
    op.create_index('idx_audit_fecha', 'audit_logs', ['creado_en'], unique=False)
    op.create_index('idx_audit_usuario', 'audit_logs', ['id_usuario'], unique=False)
    op.create_table('barberos',
    sa.Column('id_barbero', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('id_usuario', mysql.BIGINT(display_width=20, unsigned=True), nullable=False),
    sa.Column('titulo', sa.String(length=80), server_default=sa.text("'Barbero'"), nullable=False),
    sa.Column('experiencia_anios', mysql.TINYINT(display_width=3, unsigned=True), server_default=sa.text('0'), nullable=False),
    sa.Column('rating', sa.DECIMAL(precision=3, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('total_resenas', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text('0'), nullable=False),
    sa.Column('citas_completadas', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text('0'), nullable=False),
    sa.Column('disponible', mysql.TINYINT(display_width=1), server_default=sa.text('1'), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('foto_url', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('NULL ON UPDATE current_timestamp()'), nullable=True),
    sa.CheckConstraint('`rating` >= 0 and `rating` <= 5', name='chk_barberos_rating'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='fk_barberos_usuario', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_barbero')
    )
    op.create_index('idx_barberos_disponible', 'barberos', ['disponible'], unique=False)
    op.create_index('idx_barberos_rating', 'barberos', ['rating'], unique=False)
    op.create_index('uq_barberos_usuario', 'barberos', ['id_usuario'], unique=True)
    op.create_table('clientes',
    sa.Column('id_cliente', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('id_usuario', mysql.BIGINT(display_width=20, unsigned=True), nullable=False),
    sa.Column('puntos_saldo', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text('0'), nullable=False),
    sa.Column('nivel_fidelizacion', sa.Enum('Bronce', 'Plata', 'Oro', 'Diamante', name='clientesnivelfidelizacion'), server_default=sa.text("'Bronce'"), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('NULL ON UPDATE current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='fk_clientes_usuario', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_cliente')
    )
    op.create_index('idx_clientes_nivel', 'clientes', ['nivel_fidelizacion'], unique=False)
    op.create_index('idx_clientes_puntos', 'clientes', ['puntos_saldo'], unique=False)
    op.create_index('uq_clientes_usuario', 'clientes', ['id_usuario'], unique=True)
    op.create_table('email_logs',
    sa.Column('id_email', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('destinatario', sa.String(length=180), nullable=False),
    sa.Column('tipo', sa.Enum('password_reset', 'email_verification', 'confirmacion_cita', 'cancelacion_cita', 'recordatorio_cita', 'factura', 'notificacion_sistema', name='emaillogstipo'), nullable=False),
    sa.Column('asunto', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'enviado', 'fallido', name='emaillogsestado'), server_default=sa.text("'pendiente'"), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('id_usuario', mysql.BIGINT(display_width=20, unsigned=True), nullable=True),
    sa.Column('proveedor', sa.String(length=80), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('enviado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='fk_email_logs_usuario', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_email')
    )
    op.create_index('idx_email_creado', 'email_logs', ['creado_en'], unique=False)
    op.create_index('idx_email_destinatario', 'email_logs', ['destinatario'], unique=False)
    op.create_index('idx_email_tipo_estado', 'email_logs', ['tipo', 'estado'], unique=False)
    op.create_index('idx_email_usuario', 'email_logs', ['id_usuario'], unique=False)
    op.create_table('login_attempts',
    sa.Column('id_attempt', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('correo_intentado', sa.String(length=180), nullable=False),
    sa.Column('exitoso', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('id_usuario', mysql.BIGINT(display_width=20, unsigned=True), nullable=True),
    sa.Column('motivo', sa.String(length=120), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='fk_login_attempts_usuario', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_attempt')
    )
    op.create_index('idx_login_correo', 'login_attempts', ['correo_intentado'], unique=False)
    op.create_index('idx_login_exitoso', 'login_attempts', ['exitoso'], unique=False)
    op.create_index('idx_login_fecha', 'login_attempts', ['creado_en'], unique=False)
    op.create_index('idx_login_ip', 'login_attempts', ['ip'], unique=False)
    op.create_index('idx_login_usuario', 'login_attempts', ['id_usuario'], unique=False)
    op.create_table('notificaciones',
    sa.Column('id_notificacion', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('id_usuario', mysql.BIGINT(display_width=20, unsigned=True), nullable=False),
    sa.Column('tipo', sa.Enum('cita', 'pago', 'puntos', 'resena', 'seguridad', 'sistema', name='notificacionestipo'), server_default=sa.text("'sistema'"), nullable=False),
    sa.Column('titulo', sa.String(length=160), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('leida', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('leida_en', sa.DateTime(), nullable=True),
    sa.Column('url_accion', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='fk_notificaciones_usuario', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_notificacion')
    )
    op.create_index('idx_notificaciones_fecha', 'notificaciones', ['creado_en'], unique=False)
    op.create_index('idx_notificaciones_leida', 'notificaciones', ['leida'], unique=False)
    op.create_index('idx_notificaciones_tipo', 'notificaciones', ['tipo'], unique=False)
    op.create_index('idx_notificaciones_usuario', 'notificaciones', ['id_usuario'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id_token', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('id_usuario', mysql.BIGINT(display_width=20, unsigned=True), nullable=False),
    sa.Column('token_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('request_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.CheckConstraint('`expires_at` > `creado_en`', name='chk_password_reset_fechas'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='fk_password_reset_usuario', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_token')
    )
    op.create_index('idx_password_reset_created', 'password_reset_tokens', ['creado_en'], unique=False)
    op.create_index('idx_password_reset_expires', 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index('idx_password_reset_used', 'password_reset_tokens', ['used_at'], unique=False)
    op.create_index('idx_password_reset_usuario', 'password_reset_tokens', ['id_usuario'], unique=False)
    op.create_index('uq_password_reset_token_hash', 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_table('barbero_servicio',
    sa.Column('id_barbero_servicio', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('id_barbero', mysql.BIGINT(display_width=20, unsigned=True), nullable=False),
    sa.Column('id_servicio', mysql.BIGINT(display_width=20, unsigned=True), nullable=False),
    sa.Column('activo', mysql.TINYINT(display_width=1), server_default=sa.text('1'), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('precio_personalizado', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('NULL ON UPDATE current_timestamp()'), nullable=True),
    sa.CheckConstraint('`precio_personalizado` is null or `precio_personalizado` > 0', name='chk_barbero_servicio_precio'),
    sa.ForeignKeyConstraint(['id_barbero'], ['barberos.id_barbero'], name='fk_barbero_servicio_barbero', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicios.id_servicio'], name='fk_barbero_servicio_servicio', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_barbero_servicio')
    )
    op.create_index('idx_barbero_servicio_activo', 'barbero_servicio', ['activo'], unique=False)
    op.create_index('idx_barbero_servicio_barbero', 'barbero_servicio', ['id_barbero'], unique=False)
    op.create_index('idx_barbero_servicio_servicio', 'barbero_servicio', ['id_servicio'], unique=False)
    op.create_index('uq_barbero_servicio', 'barbero_servicio', ['id_barbero', 'id_servicio'], unique=True)
    op.create_table('bloqueos_agenda',
    sa.Column('id_bloqueo', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('id_barbero', mysql.BIGINT(display_width=20, unsigned=True), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.CheckConstraint('`hora_fin` > `hora_inicio`', name='chk_bloqueos_rango'),
    sa.ForeignKeyConstraint(['id_barbero'], ['barberos.id_barbero'], name='fk_bloqueos_barbero', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_bloqueo')
    )
    op.create_index('idx_bloqueos_barbero_fecha', 'bloqueos_agenda', ['id_barbero', 'fecha'], unique=False)
    op.create_index('idx_bloqueos_fecha', 'bloqueos_agenda', ['fecha'], unique=False)
    op.create_table('citas',
    sa.Column('id_cita', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('codigo_reserva', sa.String(length=30), nullable=False),
    sa.Column('id_cliente', mysql.BIGINT(display_width=20, unsigned=True), nullable=False),
    sa.Column('id_barbero', mysql.BIGINT(display_width=20, unsigned=True), nullable=False),
    sa.Column('id_servicio', mysql.BIGINT(display_width=20, unsigned=True), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'confirmada', 'en_atencion', 'completada', 'cancelada', 'no_asistio', name='citasestado'), server_default=sa.text("'pendiente'"), nullable=False),
    sa.Column('precio_total', sa.DECIMAL(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('descuento_aplicado', sa.DECIMAL(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('puntos_canjeados', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text('0'), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('motivo_cancelacion', sa.String(length=255), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('NULL ON UPDATE current_timestamp()'), nullable=True),
    sa.Column('cancelado_en', sa.DateTime(), nullable=True),
    sa.CheckConstraint('`descuento_aplicado` >= 0', name='chk_citas_descuento'),
    sa.CheckConstraint('`hora_fin` > `hora_inicio`', name='chk_citas_horario'),
    sa.CheckConstraint('`precio_total` >= 0', name='chk_citas_precio'),
    sa.ForeignKeyConstraint(['id_barbero'], ['barberos.id_barbero'], name='fk_citas_barbero', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], name='fk_citas_cliente', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicios.id_servicio'], name='fk_citas_servicio', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id_cita')
    )
    op.create_index('idx_citas_barbero_fecha', 'citas', ['id_barbero', 'fecha'], unique=False)
    op.create_index('idx_citas_cliente_fecha', 'citas', ['id_cliente', 'fecha'], unique=False)
    op.create_index('idx_citas_estado', 'citas', ['estado'], unique=False)
    op.create_index('idx_citas_fecha_hora', 'citas', ['fecha', 'hora_inicio', 'hora_fin'], unique=False)
    op.create_index('idx_citas_servicio', 'citas', ['id_servicio'], unique=False)
    op.create_index('uq_citas_codigo_reserva', 'citas', ['codigo_reserva'], unique=True)
    op.create_table('horarios_barbero',
    sa.Column('id_horario', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('id_barbero', mysql.BIGINT(display_width=20, unsigned=True), nullable=False),
    sa.Column('dia_semana', mysql.TINYINT(display_width=3, unsigned=True), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('activo', mysql.TINYINT(display_width=1), server_default=sa.text('1'), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('NULL ON UPDATE current_timestamp()'), nullable=True),
    sa.CheckConstraint('`dia_semana` between 1 and 7', name='chk_horarios_dia'),
    sa.CheckConstraint('`hora_fin` > `hora_inicio`', name='chk_horarios_rango'),
    sa.ForeignKeyConstraint(['id_barbero'], ['barberos.id_barbero'], name='fk_horarios_barbero', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_horario')
    )
    op.create_index('idx_horarios_activo', 'horarios_barbero', ['activo'], unique=False)
    op.create_index('idx_horarios_barbero_dia', 'horarios_barbero', ['id_barbero', 'dia_semana'], unique=False)
    op.create_index('uq_horario_barbero_dia_rango', 'horarios_barbero', ['id_barbero', 'dia_semana', 'hora_inicio', 'hora_fin'], unique=True)
    op.create_table('facturas',
    sa.Column('id_factura', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('numero_factura', sa.String(length=40), nullable=False),
    sa.Column('id_cita', mysql.BIGINT(display_width=20, unsigned=True), nullable=False),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('descuento', sa.DECIMAL(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('impuestos', sa.DECIMAL(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('total', sa.DECIMAL(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('metodo_pago', sa.Enum('efectivo', 'tarjeta', 'transferencia', 'nequi', 'daviplata', 'otro', name='facturasmetodopago'), server_default=sa.text("'efectivo'"), nullable=False),
    sa.Column('estado_pago', sa.Enum('pendiente', 'pagada', 'anulada', 'reembolsada', name='facturasestadopago'), server_default=sa.text("'pendiente'"), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('pagado_en', sa.DateTime(), nullable=True),
    sa.Column('anulada_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('NULL ON UPDATE current_timestamp()'), nullable=True),
    sa.CheckConstraint('`descuento` >= 0', name='chk_facturas_descuento'),
    sa.CheckConstraint('`impuestos` >= 0', name='chk_facturas_impuestos'),
    sa.CheckConstraint('`subtotal` >= 0', name='chk_facturas_subtotal'),
    sa.CheckConstraint('`total` >= 0', name='chk_facturas_total'),
    sa.ForeignKeyConstraint(['id_cita'], ['citas.id_cita'], name='fk_facturas_cita', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id_factura')
    )
    op.create_index('idx_facturas_estado_pago', 'facturas', ['estado_pago'], unique=False)
    op.create_index('idx_facturas_fecha', 'facturas', ['fecha_emision'], unique=False)
    op.create_index('uq_facturas_cita', 'facturas', ['id_cita'], unique=True)
    op.create_index('uq_facturas_numero', 'facturas', ['numero_factura'], unique=True)
    op.create_table('penalidades',
    sa.Column('id_penalidad', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('id_cliente', mysql.BIGINT(display_width=20, unsigned=True), nullable=False),
    sa.Column('tipo', sa.Enum('no_asistencia', 'cancelacion_tardia', 'incumplimiento', 'otro', name='penalidadestipo'), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('puntos_descontados', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text('0'), nullable=False),
    sa.Column('monto', sa.DECIMAL(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'aplicada', 'anulada', name='penalidadesestado'), server_default=sa.text("'pendiente'"), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('id_cita', mysql.BIGINT(display_width=20, unsigned=True), nullable=True),
    sa.Column('aplicada_en', sa.DateTime(), nullable=True),
    sa.Column('anulada_en', sa.DateTime(), nullable=True),
    sa.CheckConstraint('`monto` >= 0', name='chk_penalidades_monto'),
    sa.ForeignKeyConstraint(['id_cita'], ['citas.id_cita'], name='fk_penalidades_cita', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], name='fk_penalidades_cliente', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_penalidad')
    )
    op.create_index('idx_penalidades_cita', 'penalidades', ['id_cita'], unique=False)
    op.create_index('idx_penalidades_cliente', 'penalidades', ['id_cliente'], unique=False)
    op.create_index('idx_penalidades_estado', 'penalidades', ['estado'], unique=False)
    op.create_index('idx_penalidades_tipo', 'penalidades', ['tipo'], unique=False)
    op.create_table('puntos_movimientos',
    sa.Column('id_movimiento', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('id_cliente', mysql.BIGINT(display_width=20, unsigned=True), nullable=False),
    sa.Column('tipo', sa.Enum('ganancia', 'canje', 'ajuste', 'penalizacion', 'expiracion', name='puntosmovimientostipo'), nullable=False),
    sa.Column('puntos', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('id_cita', mysql.BIGINT(display_width=20, unsigned=True), nullable=True),
    sa.Column('id_usuario_responsable', mysql.BIGINT(display_width=20, unsigned=True), nullable=True),
    sa.Column('saldo_resultante', mysql.INTEGER(display_width=10, unsigned=True), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.CheckConstraint('`puntos` <> 0', name='chk_puntos_no_cero'),
    sa.ForeignKeyConstraint(['id_cita'], ['citas.id_cita'], name='fk_puntos_cita', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], name='fk_puntos_cliente', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario_responsable'], ['usuarios.id_usuario'], name='fk_puntos_responsable', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_movimiento')
    )
    op.create_index('idx_puntos_cita', 'puntos_movimientos', ['id_cita'], unique=False)
    op.create_index('idx_puntos_cliente', 'puntos_movimientos', ['id_cliente'], unique=False)
    op.create_index('idx_puntos_fecha', 'puntos_movimientos', ['creado_en'], unique=False)
    op.create_index('idx_puntos_responsable', 'puntos_movimientos', ['id_usuario_responsable'], unique=False)
    op.create_index('idx_puntos_tipo', 'puntos_movimientos', ['tipo'], unique=False)
    op.create_table('resenas',
    sa.Column('id_resena', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('id_cita', mysql.BIGINT(display_width=20, unsigned=True), nullable=False),
    sa.Column('id_cliente', mysql.BIGINT(display_width=20, unsigned=True), nullable=False),
    sa.Column('id_barbero', mysql.BIGINT(display_width=20, unsigned=True), nullable=False),
    sa.Column('calificacion', mysql.TINYINT(display_width=3, unsigned=True), nullable=False),
    sa.Column('visible', mysql.TINYINT(display_width=1), server_default=sa.text('1'), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('NULL ON UPDATE current_timestamp()'), nullable=True),
    sa.CheckConstraint('`calificacion` between 1 and 5', name='chk_resenas_calificacion'),
    sa.ForeignKeyConstraint(['id_barbero'], ['barberos.id_barbero'], name='fk_resenas_barbero', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['id_cita'], ['citas.id_cita'], name='fk_resenas_cita', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], name='fk_resenas_cliente', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id_resena')
    )
    op.create_index('idx_resenas_barbero', 'resenas', ['id_barbero'], unique=False)
    op.create_index('idx_resenas_calificacion', 'resenas', ['calificacion'], unique=False)
    op.create_index('idx_resenas_cliente', 'resenas', ['id_cliente'], unique=False)
    op.create_index('idx_resenas_visible', 'resenas', ['visible'], unique=False)
    op.create_index('uq_resenas_cita', 'resenas', ['id_cita'], unique=True)
    op.create_table('detalle_factura',
    sa.Column('id_detalle', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('id_factura', mysql.BIGINT(display_width=20, unsigned=True), nullable=False),
    sa.Column('descripcion', sa.String(length=180), nullable=False),
    sa.Column('cantidad', mysql.SMALLINT(display_width=5, unsigned=True), server_default=sa.text('1'), nullable=False),
    sa.Column('precio_unitario', sa.DECIMAL(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('descuento', sa.DECIMAL(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('id_servicio', mysql.BIGINT(display_width=20, unsigned=True), nullable=True),
    sa.CheckConstraint('`cantidad` > 0', name='chk_detalle_cantidad'),
    sa.CheckConstraint('`descuento` >= 0', name='chk_detalle_descuento'),
    sa.CheckConstraint('`precio_unitario` >= 0', name='chk_detalle_precio'),
    sa.CheckConstraint('`subtotal` >= 0', name='chk_detalle_subtotal'),
    sa.ForeignKeyConstraint(['id_factura'], ['facturas.id_factura'], name='fk_detalle_factura', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicios.id_servicio'], name='fk_detalle_servicio', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_index('idx_detalle_factura', 'detalle_factura', ['id_factura'], unique=False)
    op.create_index('idx_detalle_servicio', 'detalle_factura', ['id_servicio'], unique=False)
    # ### end Alembic commands ###



    # Las vistas se crean con SQL crudo: Alembic no las modela.
    op.execute("""CREATE OR REPLACE VIEW v_citas_detalle AS
SELECT
    ci.id_cita,
    ci.codigo_reserva,
    ci.fecha,
    ci.hora_inicio,
    ci.hora_fin,
    TIMESTAMP(ci.fecha, ci.hora_inicio) AS inicio_at,
    TIMESTAMP(ci.fecha, ci.hora_fin) AS fin_at,
    ci.estado,
    ci.precio_total,
    ci.descuento_aplicado,
    ci.puntos_canjeados,
    ci.observaciones,
    ci.motivo_cancelacion,
    ci.creado_en,
    ci.actualizado_en,
    ci.cancelado_en,

    cl.id_cliente,
    cliente_user.id_usuario AS id_usuario_cliente,
    cliente_user.nombre AS cliente_nombre,
    cliente_user.correo AS cliente_correo,
    cliente_user.telefono AS cliente_telefono,
    cl.puntos_saldo AS cliente_puntos_saldo,
    cl.nivel_fidelizacion AS cliente_nivel_fidelizacion,

    b.id_barbero,
    barbero_user.id_usuario AS id_usuario_barbero,
    barbero_user.nombre AS barbero_nombre,
    barbero_user.correo AS barbero_correo,
    barbero_user.telefono AS barbero_telefono,
    b.titulo AS barbero_titulo,
    b.rating AS barbero_rating,
    b.disponible AS barbero_disponible,

    s.id_servicio,
    s.nombre AS servicio_nombre,
    s.categoria AS servicio_categoria,
    s.precio AS servicio_precio_base,
    s.duracion_minutos AS servicio_duracion_minutos,
    s.puntos_otorga AS servicio_puntos_otorga,

    f.id_factura,
    f.numero_factura,
    f.estado_pago,
    f.metodo_pago,
    f.total AS factura_total
FROM citas ci
JOIN clientes cl
    ON cl.id_cliente = ci.id_cliente
JOIN usuarios cliente_user
    ON cliente_user.id_usuario = cl.id_usuario
JOIN barberos b
    ON b.id_barbero = ci.id_barbero
JOIN usuarios barbero_user
    ON barbero_user.id_usuario = b.id_usuario
JOIN servicios s
    ON s.id_servicio = ci.id_servicio
LEFT JOIN facturas f
    ON f.id_cita = ci.id_cita""")
    op.execute("""CREATE OR REPLACE VIEW v_dashboard_admin AS
SELECT
    (SELECT COUNT(*) FROM usuarios WHERE activo = TRUE) AS total_usuarios_activos,
    (SELECT COUNT(*) FROM clientes) AS total_clientes,
    (SELECT COUNT(*) FROM barberos WHERE disponible = TRUE) AS total_barberos_disponibles,
    (SELECT COUNT(*) FROM servicios WHERE activo = TRUE) AS total_servicios_activos,
    (SELECT COUNT(*) FROM citas) AS total_citas,
    (SELECT COUNT(*) FROM citas WHERE estado = 'pendiente') AS citas_pendientes,
    (SELECT COUNT(*) FROM citas WHERE estado = 'confirmada') AS citas_confirmadas,
    (SELECT COUNT(*) FROM citas WHERE estado = 'completada') AS citas_completadas,
    (SELECT COUNT(*) FROM citas WHERE estado = 'cancelada') AS citas_canceladas,
    (SELECT COUNT(*) FROM citas WHERE estado = 'no_asistio') AS citas_no_asistio,
    (SELECT COALESCE(SUM(total), 0) FROM facturas WHERE estado_pago = 'pagada') AS ingresos_pagados,
    (SELECT COUNT(*) FROM password_reset_tokens) AS total_tokens_recuperacion,
    (SELECT COUNT(*) FROM email_logs WHERE estado = 'fallido') AS correos_fallidos,
    NOW() AS generado_en""")
    op.execute("""CREATE OR REPLACE VIEW v_ranking_barberos AS
SELECT
    b.id_barbero,
    u.id_usuario,
    u.nombre,
    u.correo,
    u.telefono,
    b.titulo,
    b.experiencia_anios,
    b.bio,
    b.rating AS rating_registrado,

    COALESCE(resena_stats.rating_resenas, 0) AS rating_resenas,
    COALESCE(resena_stats.total_resenas_visibles, 0) AS total_resenas_visibles,

    b.total_resenas AS total_resenas_registradas,
    b.citas_completadas,
    b.disponible,

    COALESCE(cita_stats.total_citas_asignadas, 0) AS total_citas_asignadas,
    COALESCE(cita_stats.citas_completadas_reales, 0) AS citas_completadas_reales,
    COALESCE(cita_stats.citas_canceladas, 0) AS citas_canceladas,
    COALESCE(cita_stats.citas_no_asistio, 0) AS citas_no_asistio
FROM barberos b
JOIN usuarios u
    ON u.id_usuario = b.id_usuario
LEFT JOIN (
    SELECT
        id_barbero,
        COUNT(*) AS total_citas_asignadas,
        SUM(CASE WHEN estado = 'completada' THEN 1 ELSE 0 END) AS citas_completadas_reales,
        SUM(CASE WHEN estado = 'cancelada' THEN 1 ELSE 0 END) AS citas_canceladas,
        SUM(CASE WHEN estado = 'no_asistio' THEN 1 ELSE 0 END) AS citas_no_asistio
    FROM citas
    GROUP BY id_barbero
) cita_stats
    ON cita_stats.id_barbero = b.id_barbero
LEFT JOIN (
    SELECT
        id_barbero,
        AVG(calificacion) AS rating_resenas,
        COUNT(*) AS total_resenas_visibles
    FROM resenas
    WHERE visible = TRUE
    GROUP BY id_barbero
) resena_stats
    ON resena_stats.id_barbero = b.id_barbero""")
    op.execute("""CREATE OR REPLACE VIEW v_resumen_clientes AS
SELECT
    cl.id_cliente,
    u.id_usuario,
    u.nombre,
    u.correo,
    u.telefono,
    u.activo,
    cl.puntos_saldo,
    cl.nivel_fidelizacion,
    cl.fecha_registro,

    COUNT(ci.id_cita) AS total_citas,
    SUM(CASE WHEN ci.estado = 'completada' THEN 1 ELSE 0 END) AS citas_completadas,
    SUM(CASE WHEN ci.estado = 'cancelada' THEN 1 ELSE 0 END) AS citas_canceladas,
    SUM(CASE WHEN ci.estado = 'no_asistio' THEN 1 ELSE 0 END) AS citas_no_asistio,

    COALESCE(SUM(CASE WHEN f.estado_pago = 'pagada' THEN f.total ELSE 0 END), 0) AS total_pagado,
    MAX(ci.fecha) AS ultima_fecha_cita
FROM clientes cl
JOIN usuarios u
    ON u.id_usuario = cl.id_usuario
LEFT JOIN citas ci
    ON ci.id_cliente = cl.id_cliente
LEFT JOIN facturas f
    ON f.id_cita = ci.id_cita
GROUP BY
    cl.id_cliente,
    u.id_usuario,
    u.nombre,
    u.correo,
    u.telefono,
    u.activo,
    cl.puntos_saldo,
    cl.nivel_fidelizacion,
    cl.fecha_registro""")


def downgrade() -> None:
    """Revierte el esquema completo."""
    op.execute('DROP VIEW IF EXISTS v_citas_detalle')
    op.execute('DROP VIEW IF EXISTS v_dashboard_admin')
    op.execute('DROP VIEW IF EXISTS v_ranking_barberos')
    op.execute('DROP VIEW IF EXISTS v_resumen_clientes')
    op.execute('SET FOREIGN_KEY_CHECKS = 0')
    op.drop_table('detalle_factura')
    op.drop_table('resenas')
    op.drop_table('puntos_movimientos')
    op.drop_table('penalidades')
    op.drop_table('facturas')
    op.drop_table('horarios_barbero')
    op.drop_table('citas')
    op.drop_table('bloqueos_agenda')
    op.drop_table('barbero_servicio')
    op.drop_table('password_reset_tokens')
    op.drop_table('notificaciones')
    op.drop_table('login_attempts')
    op.drop_table('email_logs')
    op.drop_table('clientes')
    op.drop_table('barberos')
    op.drop_table('audit_logs')
    op.drop_table('usuarios')
    op.drop_table('catalogo_cortes')
    op.drop_table('servicios')
    op.drop_table('roles')
    op.execute('SET FOREIGN_KEY_CHECKS = 1')
